seed: 30

folder:
    input_masks           :   'labels'
    input_folder          :   'Data - Scheurdetectie v2\00c_input'
    subimg_folder         :   'Projects\Data - Scheurdetectie v2\01_subimages'
    filter_folder         :   'Projects\Data - Scheurdetectie v2\02_subimages_filtered'
    kfolds_folder         :   'Projects\Data - Scheurdetectie v2\03_K_fold_cv_filtered'
    kfolds_geo            :   'Projects\Data - Scheurdetectie v2\04_K_fold_cv_geo'
    kfolds_rgb            :   'Projects\Data - Scheurdetectie v2\05_K_fold_cv_rgb'
    sub_filter            :   'subimages_filtered'
    sub_geo               :   'subimages_augmentated_geo'
    sub_rgb               :   'subimages_augmentated_rgb'
    output_folder         :   'outputs'
    tiffiles              :   'Projects\Data - Scheurdetectie v2\00a_tif'
    tiffiles_mask         :   'Projects\Data - Scheurdetectie v2\01_subimages\masks_tiff'

unet:
    shape_filter          :   '../../../data/shapes_filtered/shapes_filter.shp'
    area_threshold        :   50  #cm
    threshold_predict     :   0.8 #U-net produces values between 0-1. To make a binary mask, a cut-off level has to be set.
    petrained_weights     :   'Unet/weights/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_0.35_224_no_top.h5' #Weights to intialize U-net
    trained_weights       :   'outputs/Unet/trained_weights/' #Weights after training are saved to this folder

image:
    fraction_no_lbl       : 0.2   #Add fraction of images (with respect to images with label) without label to the dataset
    subimage_height       : 512
    subimage_width        : 512

postprocessing:
    fraction_overlap      : 0.01  #Ammount of overlap between polygons to be considered true positive

cross_val:
    k_folds               : 5
    split                 : 0.2
    n_transforms_geo      : 2     #Data augmentation (if 5 then 5(geometric augmentation)x X(color augmentation)=25 augmentated images are created.
    n_transforms_rgb      : 2     #Data augmentation (if 5 then X(geometric augmentation)x 5(color augmentation)=25 augmentated images are created.
    preferred_fold        : 5     #We use cross-validation to predict on the whole dataset. If an image is not present in testset, the trained model of this fold will be used
