project:
  type: website

format:
  html:
    theme:
      light: united
      dark: superhero
    css: assets/styles.css
    toc: true
    code-fold: true

website:
  title: "AI Toolbox Waterkeringen"
  search: false
  navbar:
    background: primary
    title: false
    left:
      - icon: house-fill
        href: "./index.html"
        aria-label: Home
    right:
      - text: "Meer weten"
        href: more.qmd
      - text: "Over ons"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
  sidebar:
    # Alleen voor specifieke pagina "Meer weten"
    - title: "Meer weten"
      style: "floating"
      contents:
        - section: "Meer over de AI Toolbox"
          href: more.qmd
          contents:
          - examples/opschotdetectie_voorbeeld.ipynb
  page-footer: |
    <div>
      ![Stichting Toegepast Onderzoek Waterbeheer](/assets/stowa.png) 
      ![Rijkswaterstaat Ministerie van Infrastructuur en Waterstaat](/assets/rws.png) 
    </div>
    <div>
      ![Hoogheemraadschap Hollands Noorderkwartier](/assets/hhnk.jpg) 
      ![HKV lijn in water](/assets/hkv.png)
    </div>
