---
title: "Over ons"
---

Waterschappen inspecteren jaarlijks vele duizenden kilometers waterkeringen. Om inzicht te krijgen in actuele sterkte van waterkeringen wordt het steeds belangrijker om te kijken naar verschillen in conditie ten opzichte van de uitgangspunten van de toetsing en beoordeling. Dit soort inspecties zijn arbeidsintensief. Beheerders geven aan dat het handmatig vastleggen van schadebeelden en het verwerken van inspecties zeer veel tijd kost.

Daarnaast zien we in sectoren om ons heen dat ontwikkelingen rondom AI steeds sneller gaan en ook gebruikt worden in de praktijk. Ook binnen de watersector werken waterschappen en adviesbureaus aan nieuwe toepassingen voor AI (bijvoorbeeld vanuit het DEEP programma). Zo heeft Hoogheemraadschap Hollands Noorderkwartier (HHNK) enkele jaren geleden het voortouw genomen om te starten met AI ontwikkelingen voor inspectie van waterkeringen.

Vervolgens is de behoefte ontstaan om meerdere use cases uit te gaan werken en dit vervolgens te bundelen. Dit heeft geleid tot de ambitie om met geïnteresseerde waterschappen een AI Toolbox voor waterkeringen te ontwikkelen.
